"""Complete Data Models - Nigerian & International Profile Data"""

# Nigerian States and FCT
NIGERIAN_STATES = [
    ("ABIA", "Abia"),
    ("ADAMAWA", "Adamawa"),
    ("AKWA_IBOM", "Akwa Ibom"),
    ("ANAMBRA", "Anambra"),
    ("BAUCHI", "Bauchi"),
    ("BAYELSA", "Bayelsa"),
    ("BENUE", "Benue"),
    ("BORNO", "Borno"),
    ("CROSS_RIVER", "Cross River"),
    ("DELTA", "Delta"),
    ("EBONYI", "Ebonyi"),
    ("EDO", "Edo"),
    ("EKITI", "Ekiti"),
    ("ENUGU", "Enugu"),
    ("GOMBE", "Gombe"),
    ("IMO", "Imo"),
    ("JIGAWA", "Jigawa"),
    ("KADUNA", "Kaduna"),
    ("KANO", "Kano"),
    ("KATSINA", "Katsina"),
    ("KEBBI", "Kebbi"),
    ("KWARA", "Kwara"),
    ("LAGOS", "Lagos"),
    ("NASARAWA", "Nasarawa"),
    ("NIGER", "Niger"),
    ("OGUN", "Ogun"),
    ("ONDO", "Ondo"),
    ("OSUN", "Osun"),
    ("OYO", "Oyo"),
    ("PLATEAU", "Plateau"),
    ("RIVERS", "Rivers"),
    ("SOKOTO", "Sokoto"),
    ("TARABA", "Taraba"),
    ("YOBE", "Yobe"),
    ("ZAMFARA", "Zamfara"),
    ("FCT", "Federal Capital Territory"),
]

# Major Local Government Areas per State (sample - can be extended)
NIGERIAN_LGAS = {
    "ABIA": ["Aba North", "Aba South", "Arochukwu", "Bende", "Ikwuano", "Isiala-Ngwa North", "Isiala-Ngwa South", "Isuikwuato", "Nnochi", "Obingwa", "Ohafia", "Osisioma", "Ugwunagbo", "Ukwa East", "Ukwa West", "Umuahia North", "Umuahia South", "Umu-Nneocha"],
    "ADAMAWA": ["Demsa", "Ganye", "Girei", "Gombi", "Jada", "Lamurde", "Madagali", "Maiha", "Mayo-Belwa", "Michika", "Mubi North", "Mubi South", "Song", "Toungo", "Yola North", "Yola South"],
    "LAGOS": ["Agege", "Ajeromi-Ifelodun", "Alimosho", "Amuwo-Odofin", "Apapa", "Badagry", "Epe", "Eti-Osa", "Ibeju-Lekki", "Ifako-Ijaye", "Ikeja", "Ikorodu", "Kosofe", "Lagos Island", "Lagos Mainland", "Mushin", "Ojo", "Oshodi-Isolo", "Shomolu", "Surulere"],
    "OYO": ["Afijio", "Akinyele", "Atiba", "Atisbo", "Egbeda", "Ibadan North", "Ibadan North-East", "Ibadan North-West", "Ibadan South-East", "Ibadan South-West", "Ibarapa Central", "Ibarapa East", "Ibarapa North", "Ido", "Irepo", "Iseyin", "Itesiwaju", "Iwajowa", "Kajola", "Lagelu"],
    "RIVERS": ["Abua-Odual", "Ahoada-East", "Ahoada-West", "Akuku-Toru", "Asari-Toru", "Bonny", "Degema", "Eleme", "Emuoha", "Etche", "Gokana", "Ikwerre", "Khana", "Obio-Akpor", "Ogba-Egbema-Ndoni", "Okrika", "Omuma", "Opobo-Nkoro", "Oyigbo", "Port Harcourt"],
    # Add more states as needed...
}

# Blood Groups
BLOOD_GROUPS = [
    ("A+", "A Positive"),
    ("A-", "A Negative"),
    ("B+", "B Positive"),
    ("B-", "B Negative"),
    ("AB+", "AB Positive"),
    ("AB-", "AB Negative"),
    ("O+", "O Positive"),
    ("O-", "O Negative"),
]

# Genotypes
GENOTYPES = [
    ("AA", "AA - Normal"),
    ("AS", "AS - Carrier"),
    ("SS", "SS - Sickle Cell"),
    ("AC", "AC - Carrier (Rare)"),
    ("SC", "SC - Sickle Cell (Variant)"),
    ("CC", "CC - Rare"),
    ("Other", "Other"),
]

# Disability Types
DISABILITY_TYPES = [
    ("none", "None"),
    ("blind", "Blind/Visual Impairment"),
    ("deaf", "Deaf/Hearing Impairment"),
    ("mute", "Mute/Speech Impairment"),
    ("amputee", "Amputee"),
    ("paralysis", "Paralysis"),
    ("cerebral_palsy", "Cerebral Palsy"),
    ("intellectual", "Intellectual Disability"),
    ("physical", "Physical Disability"),
    ("chronic_illness", "Chronic Illness"),
    ("other", "Other"),
]

# Common Medical Conditions
MEDICAL_CONDITIONS = [
    ("none", "None"),
    ("asthma", "Asthma"),
    ("diabetes", "Diabetes"),
    ("hypertension", "Hypertension"),
    ("heart_disease", "Heart Disease"),
    ("kidney_disease", "Kidney Disease"),
    ("epilepsy", "Epilepsy"),
    ("sickle_cell", "Sickle Cell Disease"),
    ("cancer", "Cancer"),
    ("hiv_aids", "HIV/AIDS"),
    ("tb", "Tuberculosis"),
    ("allergies", "Allergies"),
    ("mental_health", "Mental Health Condition"),
    ("autoimmune", "Autoimmune Disease"),
    ("other", "Other"),
]

# Relationship to Next of Kin
NEXT_OF_KIN_RELATIONSHIPS = [
    ("father", "Father"),
    ("mother", "Mother"),
    ("spouse", "Spouse"),
    ("son", "Son"),
    ("daughter", "Daughter"),
    ("brother", "Brother"),
    ("sister", "Sister"),
    ("uncle", "Uncle"),
    ("aunt", "Aunt"),
    ("grandfather", "Grandfather"),
    ("grandmother", "Grandmother"),
    ("other", "Other"),
]

# Marital Status
MARITAL_STATUS = [
    ("single", "Single"),
    ("married", "Married"),
    ("divorced", "Divorced"),
    ("widowed", "Widowed"),
    ("separated", "Separated"),
]

# Title
TITLES = [
    ("Mr", "Mr"),
    ("Mrs", "Mrs"),
    ("Miss", "Miss"),
    ("Ms", "Ms"),
    ("Dr", "Dr"),
    ("Prof", "Prof"),
    ("Hon", "Hon"),
    ("Chief", "Chief"),
    ("Alh", "Alhaji"),
    ("Eva", "Evangelist"),
]

# Religion
RELIGIONS = [
    ("christianity", "Christianity"),
    ("islam", "Islam"),
    ("traditional", "Traditional"),
    ("catholic", "Catholic"),
    ("other", "Other"),
    ("none", "None"),
]

# Denomination (for Christians)
DENOMINATIONS = [
    ("catholic", "Catholic"),
    ("baptist", "Baptist"),
    ("methodist", "Methodist"),
    ("presbyterian", "Presbyterian"),
    ("anglican", "Anglican/Church of Nigeria"),
    ("pentecostal", "Pentecostal"),
    ("evangelical", "Evangelical"),
    (" Seventh_day", "Seventh Day Adventist"),
    ("jehovahs_witness", "Jehovah's Witness"),
    ("mormon", "Mormon/LDS"),
    ("other", "Other"),
]

# Mode of Entry (Admission)
MODE_OF_ENTRY = [
    ("ume", "UME (Uniform Matriculation Examination)"),
    ("direct_entry", "Direct Entry"),
    ("transfer", "Transfer"),
    ("part_time", "Part Time"),
    ("evening", "Evening Programme"),
    ("sandwich", "Sandwich Programme"),
]

# Student Status
STUDENT_STATUS = [
    ("active", "Active"),
    ("inactive", "Inactive"),
    ("suspended", "Suspended"),
    ("withdrawn", "Withdrawn"),
    ("graduated", "Graduated"),
    ("deferred", "Deferred"),
]

# Staff Employment Status
EMPLOYMENT_STATUS = [
    ("active", "Active"),
    ("on_leave", "On Leave"),
    ("suspended", "Suspended"),
    ("terminated", "Terminated"),
    ("retired", "Retired"),
]

# Staff Category
STAFF_CATEGORIES = [
    ("academic", "Academic"),
    ("administrative", "Administrative"),
    ("technical", "Technical"),
    ("support", "Support Staff"),
    ("contract", "Contract Staff"),
    ("adjunct", "Adjunct"),
    ("visiting", "Visiting"),
]

# Qualification Types
QUALIFICATION_TYPES = [
    ("ssce", "SSCE/WAEC/NECO"),
    ("nd", "ND"),
    ("hnd", "HND"),
    ("bsc", "B.Sc"),
    ("msc", "M.Sc"),
    ("phd", "Ph.D"),
    ("pgd", "PGD"),
    ("certificate", "Certificate"),
    ("diploma", "Diploma"),
]

# Fields of Study
FIELDS_OF_STUDY = [
    ("science", "Science"),
    ("arts", "Arts"),
    ("social_science", "Social Science"),
    ("engineering", "Engineering"),
    ("medicine", "Medicine"),
    ("law", "Law"),
    ("education", "Education"),
    ("agriculture", "Agriculture"),
    ("management", "Management"),
    ("technology", "Technology"),
]

# Country Codes (ISO 3166-1 alpha-2)
COUNTRIES = {
    "AF": "Afghanistan",
    "AL": "Albania",
    "DZ": "Algeria",
    "AO": "Angola",
    "AR": "Argentina",
    "AM": "Armenia",
    "AU": "Australia",
    "AT": "Austria",
    "AZ": "Azerbaijan",
    "BS": "Bahamas",
    "BH": "Bahrain",
    "BD": "Bangladesh",
    "BB": "Barbados",
    "BY": "Belarus",
    "BE": "Belgium",
    "BZ": "Belize",
    "BJ": "Benin",
    "BT": "Bhutan",
    "BO": "Bolivia",
    "BA": "Bosnia and Herzegovina",
    "BW": "Botswana",
    "BR": "Brazil",
    "BN": "Brunei",
    "BG": "Bulgaria",
    "BF": "Burkina Faso",
    "BI": "Burundi",
    "CV": "Cabo Verde",
    "KH": "Cambodia",
    "CM": "Cameroon",
    "CA": "Canada",
    "CF": "Central African Republic",
    "TD": "Chad",
    "CL": "Chile",
    "CN": "China",
    "CO": "Colombia",
    "KM": "Comoros",
    "CD": "Congo (Democratic Republic of the)",
    "CG": "Congo (Republic of the)",
    "CR": "Costa Rica",
    "CI": "Cote d'Ivoire",
    "HR": "Croatia",
    "CU": "Cuba",
    "CY": "Cyprus",
    "CZ": "Czechia",
    "DK": "Denmark",
    "DJ": "Djibouti",
    "DM": "Dominica",
    "DO": "Dominican Republic",
    "EC": "Ecuador",
    "EG": "Egypt",
    "SV": "El Salvador",
    "GQ": "Equatorial Guinea",
    "ER": "Eritrea",
    "EE": "Estonia",
    "SZ": "Eswatini",
    "ET": "Ethiopia",
    "FJ": "Fiji",
    "FI": "Finland",
    "FR": "France",
    "GA": "Gabon",
    "GM": "Gambia",
    "GE": "Georgia",
    "DE": "Germany",
    "GH": "Ghana",
    "GR": "Greece",
    "GD": "Grenada",
    "GT": "Guatemala",
    "GN": "Guinea",
    "GW": "Guinea-Bissau",
    "GY": "Guyana",
    "HT": "Haiti",
    "HN": "Honduras",
    "HU": "Hungary",
    "IS": "Iceland",
    "IN": "India",
    "ID": "Indonesia",
    "IR": "Iran",
    "IQ": "Iraq",
    "IE": "Ireland",
    "IL": "Israel",
    "IT": "Italy",
    "JM": "Jamaica",
    "JP": "Japan",
    "JO": "Jordan",
    "KZ": "Kazakhstan",
    "KE": "Kenya",
    "KI": "Kiribati",
    "KP": "Korea (North)",
    "KR": "Korea (South)",
    "KW": "Kuwait",
    "KG": "Kyrgyzstan",
    "LA": "Laos",
    "LV": "Latvia",
    "LB": "Lebanon",
    "LS": "Lesotho",
    "LR": "Liberia",
    "LY": "Libya",
    "LI": "Liechtenstein",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "MG": "Madagascar",
    "MW": "Malawi",
    "MY": "Malaysia",
    "MV": "Maldives",
    "ML": "Mali",
    "MT": "Malta",
    "MH": "Marshall Islands",
    "MR": "Mauritania",
    "MU": "Mauritius",
    "MX": "Mexico",
    "FM": "Micronesia",
    "MD": "Moldova",
    "MC": "Monaco",
    "MN": "Mongolia",
    "ME": "Montenegro",
    "MA": "Morocco",
    "MZ": "Mozambique",
    "MM": "Myanmar",
    "NA": "Namibia",
    "NR": "Nauru",
    "NP": "Nepal",
    "NL": "Netherlands",
    "NZ": "New Zealand",
    "NI": "Nicaragua",
    "NE": "Niger",
    "NG": "Nigeria",
    "MK": "North Macedonia",
    "NO": "Norway",
    "OM": "Oman",
    "PK": "Pakistan",
    "PW": "Palau",
    "PS": "Palestine",
    "PA": "Panama",
    "PG": "Papua New Guinea",
    "PY": "Paraguay",
    "PE": "Peru",
    "PH": "Philippines",
    "PL": "Poland",
    "PT": "Portugal",
    "QA": "Qatar",
    "RO": "Romania",
    "RU": "Russia",
    "RW": "Rwanda",
    "KN": "Saint Kitts and Nevis",
    "LC": "Saint Lucia",
    "VC": "Saint Vincent and the Grenadines",
    "WS": "Samoa",
    "SM": "San Marino",
    "ST": "Sao Tome and Principe",
    "SA": "Saudi Arabia",
    "SN": "Senegal",
    "RS": "Serbia",
    "SC": "Seychelles",
    "SL": "Sierra Leone",
    "SG": "Singapore",
    "SK": "Slovakia",
    "SI": "Slovenia",
    "SB": "Solomon Islands",
    "SO": "Somalia",
    "ZA": "South Africa",
    "SS": "South Sudan",
    "ES": "Spain",
    "LK": "Sri Lanka",
    "SD": "Sudan",
    "SR": "Suriname",
    "SE": "Sweden",
    "CH": "Switzerland",
    "SY": "Syria",
    "TW": "Taiwan",
    "TJ": "Tajikistan",
    "TZ": "Tanzania",
    "TH": "Thailand",
    "TL": "Timor-Leste",
    "TG": "Togo",
    "TO": "Tonga",
    "TT": "Trinidad and Tobago",
    "TN": "Tunisia",
    "TR": "Turkey",
    "TM": "Turkmenistan",
    "TV": "Tuvalu",
    "UG": "Uganda",
    "UA": "Ukraine",
    "AE": "United Arab Emirates",
    "GB": "United Kingdom",
    "US": "United States",
    "UY": "Uruguay",
    "UZ": "Uzbekistan",
    "VU": "Vanuatu",
    "VA": "Vatican City",
    "VE": "Venezuela",
    "VN": "Vietnam",
    "YE": "Yemen",
    "ZM": "Zambia",
    "ZW": "Zimbabwe",
}

# Default to Nigeria
DEFAULT_COUNTRY = "NG"

# All nationalities (derived from countries)
NATIONALITIES = {code: name.replace("an ", "").replace("the ", "") for code, name in COUNTRIES.items()}